/*
 * data.js — AUTO-GENERATED by gui/tools/export-data.js
 * ---------------------------------------------------------------
 * Real content, read from database/gameData.db (the game catalog)
 * and database/myFarmData.db (the player's saved progress) via
 * node:sqlite. DO NOT EDIT THIS FILE BY HAND — changes are lost the
 * next time the generator runs.
 *
 * To refresh after playing/changing the databases:
 *   node gui/tools/export-data.js
 *
 * Generated: 2026-09-24T18:26:31.802Z
 * ---------------------------------------------------------------
 */

const GameData = {
  "crops": [
    {
      "name": "Carrot",
      "season": "Spring",
      "icon": "cropSpring",
      "daysToHarvest": 3,
      "regrow": false,
      "daysToRegrowth": null,
      "sellValue": [
        [
          "Normal",
          35
        ],
        [
          "Silver",
          43
        ],
        [
          "Gold",
          52
        ],
        [
          "Iridium",
          70
        ]
      ],
      "seedPrice": [
        [
          "Foraging",
          0
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          120
        ],
        [
          "Juice",
          "Keg",
          79
        ]
      ]
    },
    {
      "name": "Cauliflower",
      "season": "Spring",
      "icon": "cropSpring",
      "daysToHarvest": 12,
      "regrow": false,
      "daysToRegrowth": null,
      "sellValue": [
        [
          "Normal",
          175
        ],
        [
          "Silver",
          218
        ],
        [
          "Gold",
          262
        ],
        [
          "Iridium",
          350
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          80
        ],
        [
          "Joja",
          100
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          400
        ],
        [
          "Juice",
          "Keg",
          394
        ]
      ]
    },
    {
      "name": "Green Bean",
      "season": "Spring",
      "icon": "cropSpring",
      "daysToHarvest": 10,
      "regrow": true,
      "daysToRegrowth": 3,
      "sellValue": [
        [
          "Normal",
          40
        ],
        [
          "Silver",
          50
        ],
        [
          "Gold",
          60
        ],
        [
          "Iridium",
          80
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          60
        ],
        [
          "Joja",
          75
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          130
        ],
        [
          "Juice",
          "Keg",
          90
        ]
      ]
    },
    {
      "name": "Parsnip",
      "season": "Spring",
      "icon": "cropSpring",
      "daysToHarvest": 4,
      "regrow": false,
      "daysToRegrowth": null,
      "sellValue": [
        [
          "Normal",
          35
        ],
        [
          "Silver",
          43
        ],
        [
          "Gold",
          52
        ],
        [
          "Iridium",
          70
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          20
        ],
        [
          "Joja",
          25
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          120
        ],
        [
          "Juice",
          "Keg",
          79
        ]
      ]
    },
    {
      "name": "Strawberry",
      "season": "Spring",
      "icon": "cropSpring",
      "daysToHarvest": 8,
      "regrow": true,
      "daysToRegrowth": 4,
      "sellValue": [
        [
          "Normal",
          120
        ],
        [
          "Silver",
          150
        ],
        [
          "Gold",
          180
        ],
        [
          "Iridium",
          240
        ]
      ],
      "seedPrice": [
        [
          "Egg Festival",
          100
        ]
      ],
      "artisanItems": [
        [
          "Jelly",
          "Preserves Jar",
          290
        ],
        [
          "Wine",
          "Keg",
          360
        ]
      ]
    },
    {
      "name": "Hops",
      "season": "Summer",
      "icon": "cropSummer",
      "daysToHarvest": 11,
      "regrow": true,
      "daysToRegrowth": 1,
      "sellValue": [
        [
          "Normal",
          25
        ],
        [
          "Silver",
          31
        ],
        [
          "Gold",
          37
        ],
        [
          "Iridium",
          50
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          60
        ],
        [
          "Joja",
          75
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          100
        ],
        [
          "Pale Ale",
          "Keg",
          300
        ]
      ]
    },
    {
      "name": "Hot Pepper",
      "season": "Summer",
      "icon": "cropSummer",
      "daysToHarvest": 5,
      "regrow": true,
      "daysToRegrowth": 3,
      "sellValue": [
        [
          "Normal",
          40
        ],
        [
          "Silver",
          50
        ],
        [
          "Gold",
          60
        ],
        [
          "Iridium",
          80
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          40
        ],
        [
          "Joja",
          50
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          130
        ],
        [
          "Juice",
          "Keg",
          90
        ]
      ]
    },
    {
      "name": "Melon",
      "season": "Summer",
      "icon": "cropSummer",
      "daysToHarvest": 12,
      "regrow": false,
      "daysToRegrowth": null,
      "sellValue": [
        [
          "Normal",
          250
        ],
        [
          "Silver",
          312
        ],
        [
          "Gold",
          375
        ],
        [
          "Iridium",
          500
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          80
        ],
        [
          "Joja",
          100
        ]
      ],
      "artisanItems": [
        [
          "Jelly",
          "Preserves Jar",
          550
        ],
        [
          "Wine",
          "Keg",
          750
        ]
      ]
    },
    {
      "name": "Starfruit",
      "season": "Summer",
      "icon": "cropSummer",
      "daysToHarvest": 13,
      "regrow": false,
      "daysToRegrowth": null,
      "sellValue": [
        [
          "Normal",
          750
        ],
        [
          "Silver",
          937
        ],
        [
          "Gold",
          1125
        ],
        [
          "Iridium",
          1500
        ]
      ],
      "seedPrice": [
        [
          "The Oasis",
          400
        ]
      ],
      "artisanItems": [
        [
          "Jelly",
          "Preserves Jar",
          1550
        ],
        [
          "Wine",
          "Keg",
          2250
        ]
      ]
    },
    {
      "name": "Tomato",
      "season": "Summer",
      "icon": "cropSummer",
      "daysToHarvest": 11,
      "regrow": true,
      "daysToRegrowth": 4,
      "sellValue": [
        [
          "Normal",
          60
        ],
        [
          "Silver",
          75
        ],
        [
          "Gold",
          90
        ],
        [
          "Iridium",
          120
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          50
        ],
        [
          "Joja",
          62
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          170
        ],
        [
          "Juice",
          "Keg",
          135
        ]
      ]
    },
    {
      "name": "Bok Choi",
      "season": "Fall",
      "icon": "cropFall",
      "daysToHarvest": 4,
      "regrow": false,
      "daysToRegrowth": null,
      "sellValue": [
        [
          "Normal",
          80
        ],
        [
          "Silver",
          100
        ],
        [
          "Gold",
          120
        ],
        [
          "Iridium",
          160
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          50
        ],
        [
          "Joja",
          62
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          210
        ],
        [
          "Juice",
          "Keg",
          180
        ]
      ]
    },
    {
      "name": "Broccoli",
      "season": "Fall",
      "icon": "cropFall",
      "daysToHarvest": 8,
      "regrow": true,
      "daysToRegrowth": 4,
      "sellValue": [
        [
          "Normal",
          70
        ],
        [
          "Silver",
          87
        ],
        [
          "Gold",
          105
        ],
        [
          "Iridium",
          140
        ]
      ],
      "seedPrice": [
        [
          "Foraging",
          0
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          190
        ],
        [
          "Juice",
          "Keg",
          158
        ]
      ]
    },
    {
      "name": "Cranberries",
      "season": "Fall",
      "icon": "cropFall",
      "daysToHarvest": 7,
      "regrow": true,
      "daysToRegrowth": 5,
      "sellValue": [
        [
          "Normal",
          75
        ],
        [
          "Silver",
          93
        ],
        [
          "Gold",
          112
        ],
        [
          "Iridium",
          150
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          240
        ],
        [
          "Joja",
          300
        ]
      ],
      "artisanItems": [
        [
          "Jelly",
          "Preserves Jar",
          200
        ],
        [
          "Wine",
          "Keg",
          225
        ]
      ]
    },
    {
      "name": "Pumpkin",
      "season": "Fall",
      "icon": "cropFall",
      "daysToHarvest": 13,
      "regrow": false,
      "daysToRegrowth": null,
      "sellValue": [
        [
          "Normal",
          320
        ],
        [
          "Silver",
          400
        ],
        [
          "Gold",
          480
        ],
        [
          "Iridium",
          640
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          100
        ],
        [
          "Joja",
          125
        ]
      ],
      "artisanItems": [
        [
          "Pickles",
          "Preserves Jar",
          690
        ],
        [
          "Juice",
          "Keg",
          720
        ]
      ]
    },
    {
      "name": "Grape",
      "season": "Fall",
      "icon": "cropFall",
      "daysToHarvest": 10,
      "regrow": true,
      "daysToRegrowth": 3,
      "sellValue": [
        [
          "Normal",
          80
        ],
        [
          "Silver",
          100
        ],
        [
          "Gold",
          120
        ],
        [
          "Iridium",
          160
        ]
      ],
      "seedPrice": [
        [
          "Pierre",
          60
        ],
        [
          "Joja",
          75
        ]
      ],
      "artisanItems": [
        [
          "Jelly",
          "Preserves Jar",
          210
        ],
        [
          "Wine",
          "Keg",
          240
        ]
      ]
    },
    {
      "name": "Powdermelon",
      "season": "Winter",
      "icon": "cropWinter",
      "daysToHarvest": 7,
      "regrow": false,
      "daysToRegrowth": null,
      "sellValue": [
        [
          "Normal",
          60
        ],
        [
          "Silver",
          75
        ],
        [
          "Gold",
          90
        ],
        [
          "Iridium",
          120
        ]
      ],
      "seedPrice": [
        [
          "Foraging",
          0
        ]
      ],
      "artisanItems": [
        [
          "Jelly",
          "Preserves Jar",
          170
        ],
        [
          "Wine",
          "Keg",
          180
        ]
      ]
    }
  ],
  "villagers": [
    {
      "name": "Abigail",
      "single": true,
      "giftLove": "Amethyst",
      "giftLike": "Frozen Tear"
    },
    {
      "name": "Alex",
      "single": true,
      "giftLove": "Complete Breakfast",
      "giftLike": "Egg"
    },
    {
      "name": "Caroline",
      "single": false,
      "giftLove": "Green Tea",
      "giftLike": "Tea Leaves"
    },
    {
      "name": "Elliot",
      "single": true,
      "giftLove": "Pomegranate",
      "giftLike": "Frozen Tear"
    },
    {
      "name": "Emily",
      "single": true,
      "giftLove": "Cloth",
      "giftLike": "Frozen Tear"
    },
    {
      "name": "Evelyn",
      "single": false,
      "giftLove": "Diamond",
      "giftLike": "Milk"
    },
    {
      "name": "George",
      "single": false,
      "giftLove": "Leek",
      "giftLike": "Daffodil"
    },
    {
      "name": "Haley",
      "single": true,
      "giftLove": "Coconut",
      "giftLike": "Daffodil"
    },
    {
      "name": "Harvey",
      "single": true,
      "giftLove": "Wine",
      "giftLike": "Green Tea"
    },
    {
      "name": "Jodi",
      "single": false,
      "giftLove": "Diamond",
      "giftLike": "Egg"
    },
    {
      "name": "Leah",
      "single": true,
      "giftLove": "Wine",
      "giftLike": "Egg"
    },
    {
      "name": "Lewis",
      "single": false,
      "giftLove": "Green Tea",
      "giftLike": "Diamond"
    },
    {
      "name": "Marnie",
      "single": false,
      "giftLove": "Diamond",
      "giftLike": "Egg"
    },
    {
      "name": "Pam",
      "single": false,
      "giftLove": "Beer",
      "giftLike": "Milk"
    },
    {
      "name": "Penny",
      "single": true,
      "giftLove": "Diamond",
      "giftLike": "Milk"
    },
    {
      "name": "Robin",
      "single": false,
      "giftLove": "Goat Cheese",
      "giftLike": "Milk"
    },
    {
      "name": "Sam",
      "single": true,
      "giftLove": "Pizza",
      "giftLike": "Joja Cola"
    },
    {
      "name": "Sebastian",
      "single": true,
      "giftLove": "Frozen Tear",
      "giftLike": "Green Tea"
    },
    {
      "name": "Shane",
      "single": true,
      "giftLove": "Beer",
      "giftLike": "Egg"
    },
    {
      "name": "Willy",
      "single": false,
      "giftLove": "Diamond",
      "giftLike": "Amethyst"
    },
    {
      "name": "Wizard",
      "single": false,
      "giftLove": "Solar Essence",
      "giftLike": "Frozen Tear"
    }
  ],
  "animals": [
    {
      "name": "Cow",
      "type": "Barn",
      "icon": "animalCow",
      "produces": "Milk",
      "daysToAdult": 5,
      "buyPrice": 1500,
      "artisanItem": [
        [
          "Cheese",
          "Cheese Press",
          322
        ]
      ]
    },
    {
      "name": "Ostrich",
      "type": "Barn",
      "icon": "animalGeneric",
      "produces": "Ostrich Egg",
      "daysToAdult": 7,
      "buyPrice": null,
      "artisanItem": [
        [
          "Mayonnaise",
          "Mayonnaise Machine",
          266
        ]
      ]
    },
    {
      "name": "Goat",
      "type": "Big Barn",
      "icon": "animalGeneric",
      "produces": "Goat Milk",
      "daysToAdult": 5,
      "buyPrice": 4000,
      "artisanItem": [
        [
          "Goat Cheese",
          "Cheese Press",
          560
        ]
      ]
    },
    {
      "name": "Sheep",
      "type": "Deluxe Barn",
      "icon": "animalSheep",
      "produces": "Wool",
      "daysToAdult": 4,
      "buyPrice": 8000,
      "artisanItem": [
        [
          "Cloth",
          "Loom",
          658
        ]
      ]
    },
    {
      "name": "Pig",
      "type": "Deluxe Barn",
      "icon": "animalPig",
      "produces": "Truffle",
      "daysToAdult": 10,
      "buyPrice": 16000,
      "artisanItem": [
        [
          "Truffle Oil",
          "Oil Maker",
          1491
        ]
      ]
    },
    {
      "name": "Chicken",
      "type": "Coop",
      "icon": "animalChicken",
      "produces": "Egg",
      "daysToAdult": 3,
      "buyPrice": 800,
      "artisanItem": [
        [
          "Mayonnaise",
          "Mayonnaise Machine",
          266
        ]
      ]
    },
    {
      "name": "Duck",
      "type": "Big Coop",
      "icon": "animalGeneric",
      "produces": "Duck Egg",
      "daysToAdult": 5,
      "buyPrice": 1200,
      "artisanItem": [
        [
          "Duck Mayonnaise",
          "Mayonnaise Machine",
          525
        ]
      ]
    },
    {
      "name": "Dinosaur",
      "type": "Big Coop",
      "icon": "animalGeneric",
      "produces": "Dinosaur Egg",
      "daysToAdult": 0,
      "buyPrice": null,
      "artisanItem": [
        [
          "Dinosaur Mayonnaise",
          "Mayonnaise Machine",
          1120
        ]
      ]
    },
    {
      "name": "Rabbit",
      "type": "Deluxe Coop",
      "icon": "animalGeneric",
      "produces": "Rabbit'S Foot",
      "daysToAdult": 6,
      "buyPrice": 8000,
      "artisanItem": []
    }
  ],
  "buildings": [
    {
      "name": "Barn",
      "icon": "buildingBarn",
      "constructionMaterials": [
        [
          "Gold",
          6000
        ],
        [
          "Wood",
          350
        ],
        [
          "Stone",
          150
        ]
      ],
      "size": [
        7,
        4
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": true,
      "animalTypes": [
        "Cow",
        "Ostrich"
      ],
      "animalAmount": 4
    },
    {
      "name": "Big Barn",
      "icon": "buildingBarn",
      "constructionMaterials": [
        [
          "Gold",
          12000
        ],
        [
          "Wood",
          450
        ],
        [
          "Stone",
          200
        ]
      ],
      "size": [
        7,
        4
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": true,
      "animalTypes": [
        "Cow",
        "Ostrich",
        "Goat"
      ],
      "animalAmount": 8
    },
    {
      "name": "Deluxe Barn",
      "icon": "buildingBarn",
      "constructionMaterials": [
        [
          "Gold",
          25000
        ],
        [
          "Wood",
          550
        ],
        [
          "Stone",
          300
        ]
      ],
      "size": [
        7,
        4
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": true,
      "animalTypes": [
        "Cow",
        "Ostrich",
        "Goat",
        "Sheep",
        "Pig"
      ],
      "animalAmount": 12
    },
    {
      "name": "Coop",
      "icon": "buildingCoop",
      "constructionMaterials": [
        [
          "Gold",
          4000
        ],
        [
          "Wood",
          300
        ],
        [
          "Stone",
          100
        ]
      ],
      "size": [
        6,
        3
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": true,
      "animalTypes": [
        "Chicken"
      ],
      "animalAmount": 4
    },
    {
      "name": "Big Coop",
      "icon": "buildingCoop",
      "constructionMaterials": [
        [
          "Gold",
          10000
        ],
        [
          "Wood",
          400
        ],
        [
          "Stone",
          150
        ]
      ],
      "size": [
        6,
        3
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": true,
      "animalTypes": [
        "Chicken",
        "Duck",
        "Dinosaur"
      ],
      "animalAmount": 8
    },
    {
      "name": "Deluxe Coop",
      "icon": "buildingCoop",
      "constructionMaterials": [
        [
          "Gold",
          20000
        ],
        [
          "Wood",
          500
        ],
        [
          "Stone",
          200
        ]
      ],
      "size": [
        6,
        3
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": true,
      "animalTypes": [
        "Chicken",
        "Duck",
        "Dinosaur",
        "Rabbit"
      ],
      "animalAmount": 12
    },
    {
      "name": "Fish Pond",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          5000
        ],
        [
          "Stone",
          200
        ],
        [
          "Green Algae",
          5
        ],
        [
          "Seaweed",
          5
        ]
      ],
      "size": [
        5,
        5
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": true,
      "animalTypes": [
        "Fish"
      ],
      "animalAmount": 3
    },
    {
      "name": "Shed",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          15000
        ],
        [
          "Wood",
          300
        ]
      ],
      "size": [
        7,
        3
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    },
    {
      "name": "Big Shed",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          20000
        ],
        [
          "Wood",
          550
        ],
        [
          "Stone",
          300
        ]
      ],
      "size": [
        7,
        3
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    },
    {
      "name": "Silo",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          100
        ],
        [
          "Clay",
          10
        ],
        [
          "Stone",
          100
        ],
        [
          "Copper Bar",
          5
        ]
      ],
      "size": [
        3,
        3
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    },
    {
      "name": "Stable",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          10000
        ],
        [
          "Hardwood",
          100
        ],
        [
          "Iron Bar",
          5
        ]
      ],
      "size": [
        4,
        2
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": true,
      "animalTypes": [
        "Horse"
      ],
      "animalAmount": 1
    },
    {
      "name": "Well",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          1000
        ],
        [
          "Stone",
          75
        ]
      ],
      "size": [
        3,
        3
      ],
      "whereToGet": "Robin (Carpenter's Shop)",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    },
    {
      "name": "Earth Obelisk",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          500000
        ],
        [
          "Earth Crystal",
          10
        ],
        [
          "Iridium Bar",
          10
        ]
      ],
      "size": [
        3,
        2
      ],
      "whereToGet": "Wizard's Tower",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    },
    {
      "name": "Water Obelisk",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          500000
        ],
        [
          "Coral",
          10
        ],
        [
          "Clam",
          10
        ],
        [
          "Iridium Bar",
          5
        ]
      ],
      "size": [
        3,
        2
      ],
      "whereToGet": "Wizard's Tower",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    },
    {
      "name": "Desert Obelisk",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          1000000
        ],
        [
          "Coconut",
          10
        ],
        [
          "Cactus Fruit",
          10
        ],
        [
          "Iridium Bar",
          20
        ]
      ],
      "size": [
        3,
        2
      ],
      "whereToGet": "Wizard's Tower",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    },
    {
      "name": "Island Obelisk",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          1000000
        ],
        [
          "Dragon Tooth",
          10
        ],
        [
          "Banana",
          10
        ],
        [
          "Iridium Bar",
          10
        ]
      ],
      "size": [
        3,
        2
      ],
      "whereToGet": "Wizard's Tower",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    },
    {
      "name": "Junimo Hut",
      "icon": "buildingSilo",
      "constructionMaterials": [
        [
          "Gold",
          20000
        ],
        [
          "Stone",
          200
        ],
        [
          "Fiber",
          100
        ],
        [
          "Starfruit",
          9
        ]
      ],
      "size": [
        3,
        2
      ],
      "whereToGet": "Wizard's Tower",
      "housesAnimals": false,
      "animalTypes": [],
      "animalAmount": 0
    }
  ],
  "myFarm": {
    "farmName": "Minha Fazenda",
    "farmLayout": "Padrao",
    "myAnimals": [],
    "myBuildings": [],
    "myRelationships": []
  }
};
